import { NextResponse } from "next/server";
import prisma from '@/lib/db/prisma';
import { getAuthUser, authorize } from "@/lib/auth-util";

function isValidUUID(str) {
    return typeof str === 'string' && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(str);
}

export async function GET(request) {
  try {
    const authUser = await getAuthUser();
    authorize(authUser, ["admin", "hr", "super_admin"]);

    const { searchParams } = new URL(request.url);
    const page = parseInt(searchParams.get("page") || "1");
    const limit = parseInt(searchParams.get("limit") || "20");
    const action = searchParams.get("action");
    const entity = searchParams.get("entity");
    const search = searchParams.get("search");
    const dateFrom = searchParams.get("dateFrom");
    const dateTo = searchParams.get("dateTo");
    const sortBy = searchParams.get("sortBy") || "newest";

    const skip = (page - 1) * limit;

    let filter = {};

    if (action && action !== "all") {
      filter.action = action;
    }

    if (dateFrom || dateTo) {
      filter.createdAt = {};
      if (dateFrom) {
        filter.createdAt.gte = new Date(dateFrom);
      }
      if (dateTo) {
        const endDay = new Date(dateTo);
        endDay.setHours(23, 59, 59, 999);
        filter.createdAt.lte = endDay;
      }
    }

    // Tenant Scope Filter: Admin/HR can only see logs generated by users/employees in their organization.
    if (authUser.role !== "super_admin" && authUser.organizationId) {
      const users = await prisma.user.findMany({
        where: { organizationId: authUser.organizationId },
        select: { id: true, mongoId: true }
      });
      const employees = await prisma.employee.findMany({
        where: { organizationId: authUser.organizationId },
        select: { id: true, mongoId: true }
      });

      const allowedUserIds = [];
      users.forEach(u => {
        allowedUserIds.push(u.id);
        if (u.mongoId) allowedUserIds.push(u.mongoId);
      });
      employees.forEach(e => {
        allowedUserIds.push(e.id);
        if (e.mongoId) allowedUserIds.push(e.mongoId);
      });

      filter.userId = { in: allowedUserIds };
    }

    const rawLogs = await prisma.activityLog.findMany({
      where: filter,
      orderBy: { createdAt: sortBy === "oldest" ? "asc" : "desc" }
    });

    // Map raw logs, flattening the logData JSON payload properties onto the root level
    let logs = rawLogs.map(log => {
      const logDataObj = typeof log.logData === 'object' && log.logData !== null ? log.logData : {};
      return {
        _id: log.id,
        action: log.action,
        module: log.module,
        createdAt: log.createdAt,
        ...logDataObj
      };
    });

    // In-memory filter for Entity/Module if provided
    if (entity && entity !== "all") {
      const entityLower = entity.toLowerCase();
      logs = logs.filter(log => (log.entity || log.module || "").toLowerCase() === entityLower);
    }

    // In-memory filter for search terms
    if (search) {
      const searchLower = search.toLowerCase();
      logs = logs.filter(log => {
        const desc = (log.description || "").toLowerCase();
        const perfName = (log.performedBy?.name || "").toLowerCase();
        const perfEmail = (log.performedBy?.email || "").toLowerCase();
        const entId = (log.entityId || "").toLowerCase();
        return desc.includes(searchLower) ||
               perfName.includes(searchLower) ||
               perfEmail.includes(searchLower) ||
               entId.includes(searchLower);
      });
    }

    const total = logs.length;
    const paginatedLogs = logs.slice(skip, skip + limit);

    return NextResponse.json({
      success: true,
      logs: paginatedLogs,
      pagination: {
        page,
        limit,
        total,
        pages: Math.ceil(total / limit),
      },
    });
  } catch (error) {
    console.error("Error fetching activity logs:", error);
    const isAuthError = error.message.startsWith("Unauthorized") || error.message.startsWith("Forbidden");
    return NextResponse.json(
      { error: error.message },
      { status: isAuthError ? 401 : 500 }
    );
  }
}

